/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a importnotifieradaptor -c ImportNotifierAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef IMPORTNOTIFIERADAPTOR_H_1282025615
#define IMPORTNOTIFIERADAPTOR_H_1282025615

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.contacts.importprogress
 */
class ImportNotifierAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.contacts.importprogress")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.contacts.importprogress\">\n"
"    <signal name=\"importStarted\"/>\n"
"    <signal name=\"importEnded\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"contactsAdded\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"contactsRemoved\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"contactsMerged\"/>\n"
"    </signal>\n"
"    <method name=\"hasActiveImports\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ImportNotifierAdaptor(QObject *parent);
    virtual ~ImportNotifierAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool hasActiveImports();
Q_SIGNALS: // SIGNALS
    void importEnded(int contactsAdded, int contactsRemoved, int contactsMerged);
    void importStarted();
};

#endif
