/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a importnotifieradaptor -c ImportNotifierAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "importnotifierdbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ImportNotifierAdaptor
 */

ImportNotifierAdaptor::ImportNotifierAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ImportNotifierAdaptor::~ImportNotifierAdaptor()
{
    // destructor
}

bool ImportNotifierAdaptor::hasActiveImports()
{
    // handle method call com.nokia.contacts.importprogress.hasActiveImports
    bool out0;
    QMetaObject::invokeMethod(parent(), "hasActiveImports", Q_RETURN_ARG(bool, out0));
    return out0;
}

